### ISSUE TITLE
Add support for Github Issues

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#25]
# To-do
- [x] Design
- [x] Update the database.
- [x] Validate if the Github Username exist.
- [x] Save User information (name, email, profile image) in the database.
- [x] Get all your own repositories, not folks, and store them in the database.
- [x] Start scanning all the active repositories from time to time.
- [x] Add the new issue as a new task in Inbox.
- [x] Notify the user

**Comment by alainm23** [comment]
This is the design, thoughts?
![github 1](https://user-images.githubusercontent.com/33765137/50948674-50256a00-1471-11e9-8c9b-6e8272f3eeaf.png)
![github 2](https://user-images.githubusercontent.com/33765137/50948679-54ea1e00-1471-11e9-9594-7a46028d3329.png)

**Comment by ezeveliz** [comment]
Hi, I would like to know if this just supports public repos, because I can't see the private ones. Thanks!

**Comment by alainm23** [comment]
Thanks for the comment, in theory the feature brings all the repositories only excluding the folks.
I will do some tests to give you a better answer

**Comment by alainm23** [comment]
@ezeveliz I was doing the tests and I see that the Github API only returns the public repositories.

**Comment by ezeveliz** [comment]
@alainm23 Oh ok, that's strange, because the permissions give full control of private repositories, anyway, thanks and  greetings from Argentina

**Comment by alainm23** [comment]
@ezeveliz You are right, I will investigate more about the problem, greetings from Perú.

**Comment by ghost** [comment]
Sorry, this issue looks like github issue support is in planner but I can't find it anywhere in the actual app? Did this get removed?

**Comment by alainm23** [comment]
@corynz  Yes, support for Github issue was removed in Planner 2.0 and there are no plans to re-implement it.

**Comment by ghost** [comment]
@alainm23 I see, thanks for the reply. Can I ask why the Github issues support was removed? I thought it was a great feature
