### ISSUE TITLE
Findings after beta testing Planner 3

### ISSUE THREAD

**Issue by really-just-a-tech** [alainm23/planify#898]
I've been beta testing Planner 3 for a couple of days and made a list of what I found that's still missing, new features I would personally like, bugs I've found and things I think could be enhanced.
This list is meant to be purely informative, I really don't want to add pressure for development, you're doing a great job already!

When I find the time, I might start learning Vala so I can publish some pull requests. But for now, I'm switching back to Planner 2.6.9, which is the version I enjoy using most at the moment.

**Missing features from Planner 2**
_I'm pretty sure you already have these features planned for v3, but I'm listing them anyway 😉_

- [ ] Recurring tasks (#860)
- [ ] Quick add
- [x] Bulk actions / select multiple tasks
- [ ] Show completed tasks in `Today` view
- [x] Quickly reschedule overdue tasks
- [ ] Keep adding subtasks by pressing `Enter` after typing a subtask
- [ ] Order labels
- [x] Remove reminders
- [x] Subprojects
- [ ] Export backup
- [ ] Search view for `All Tasks` and `Completed` (#843)

**Ideas for new features**

- [ ] Drag & drop tasks between dates in `Scheduled` view
- [ ] Sorting options in `Scheduled` view
- [ ] Task deadlines (#888)
- [ ] View multiple days at once in `Scheduled` view
- [ ] Settings option to keep completed tasks on their original position in the list, so they don't move towards the bottom + ability to manually order them like open tasks
- [ ] Settings option to change `Next week` scheduling option to first day of the week, instead of 7 days later.

**Bugs**
_Planner 3.0.8 Flatpak on Fedora Linux 35 with GNOME 41.5_

- [x] The right click menu doesn't appear near the mouse pointer (#875)
- [ ] Performance (most things feel a bit slow and stuttery, especially the right click menu and switching days in `Scheduled` view)
- [x] Manually ordered tasks reset to their original position after restarting the app
- [x] Current date requires app restart to update
- [ ] Window dimensions increase after restarting the app
- [ ] Visual glitch with the glow around the view buttons (#900)

**Things I think could be tweaked/enhanced**
_These are very subjective_

- [x] `Today` yellow not well visible on white background. The more orange-y color from Planner 2 was better.
- [x] Visibility of grey checkboxes could also be improved
- [ ] When completed tasks are shown, empty sections with completed tasks in them should not display the message of containing no tasks
- [ ] A tiny bit more margin between tasks would be nice (the margin used when selecting a label looks good imo)
- [ ] Labels under tasks should appear in the same order as in the labels list

**Comment by payrim** [comment]
- [ ] can't change project tag and will always stay inbox no matter what
- [ ] sometimes today tasks don't pop up for some reason (gotta investigate to recreate it, happened only 2 times so not really an issue)


how do you do " Bulk actions / select multiple tasks"?

**Comment by really-just-a-tech** [comment]
@payrim 
> how do you do " Bulk actions / select multiple tasks"?

In Planner 2: hold `CTRL` and click on tasks.
In Planner 3: not possible in current beta, but since Alain checked it off in the list, I expect it to be in the next beta release.

**Comment by alainm23** [comment]
> @payrim
> 
> > how do you do " Bulk actions / select multiple tasks"?
> 
> In Planner 2: hold `CTRL` and click on tasks. In Planner 3: not possible in current beta, but since Alain checked it off in the list, I expect it to be in the next beta release.

Available in 3.0.9

**Comment by really-just-a-tech** [comment]
@payrim:
> - [ ] can't change project tag and will always stay inbox no matter what

What do you mean? I haven't experienced this issue.

**Comment by really-just-a-tech** [comment]
Hi @alainm23,

I've tested 3.0.9 for a bit (built from source, because flatpak build failed) and here are my observations thus far:

- [ ] While the star symbol instead of `Today` text is indeed easier to see in light mode, I think it doesn't look very good and the better approach would be to just make the `Today` text more orange-y yellow, perhaps the same color as the star. Also, the filled in star looks off compared to the other symbols in the view selector.
- [ ] I'm very glad you implemented bulk actions so quickly, but there are three problems with it:
  - [ ] It's quite hard to see which tasks are selected, because of the very light grey background they get, at least in light mode. Maybe light blue would work better?
  - [ ] Completing multiple tasks doesn't work. Only one of them gets marked as complete.
  - [ ] Uncompleting multiple tasks doesn't work. They all stay completed.
- [ ] A project moved to another project doesn't really get moved until restarting the app.
- [ ] The right click menu and other pop-up menus still appear at the default position of where a newly opened window would appear. In my case that is the center of the screen. I think it's because it's treated as a new window, instead of a child.

Again, thank you very much for the time and effort you put into what has the potential to become the very best task manager application 😀.

**Comment by IcedQuinn** [comment]
I just tested this from Flathub and the lack of bulk task editing is why I uninstalled it again. Came here to report it but it looks like you already know :+1:

**Comment by alainm23** [comment]
Planner has been discontinued and was replaced by Planify, I'll close this issue for the same reason.
